export const initialForm = {
  nama: "",
  phone: "",
  email: "",
  peserta: "",
  budget: "",
  tanggal: "",
  durasi: "",
  meetingPoint: "",
  catatan: "",
  tripType: "custom",
  customTripName: "",
  selectedDestinasi: null,
  tripFrom: "Individu",
  namaInstitusi: "",
};